### ISSUE TITLE
Set a license

### ISSUE THREAD

**Issue by GuiSim** [sethjwilliamson/LoRTracker#6]
Hey! This is a really cool project but I think you should set an Open Source License.
Right now the only guidance on what people can do with this code is this line from the Readme:
> I do not allow people to distribute projects using my code.

This is too vague!

If you're looking for guidance, https://choosealicense.com/ is a good starting point.

Thank you!

**Comment by sethjwilliamson** [comment]
Thank you, that is something I set up when I first started the project that I meant to update sooner but I had forgotten about.
I have updated both the license and readme to reflect my change to GNU GPL v3.

Thank you!
